services:
  - type: web
    name: shooting-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
